### ISSUE TITLE
issue with 'import ct dcm'

### ISSUE THREAD

**Issue by mtembel** [OPM/OpenDect#1]
Once launched the GUI seems to not recognize the dcm file, any suggestion?

**Comment by Thif** [comment]
Hi !
Do you have a traceback of the error ?

**Comment by mtembel** [comment]
I think the issue could be related to my data. Wonder if you have any images just for testing ?
Many thanks in advance

**Comment by mtembel** [comment]
Hi,
I got this error when trying to 'run the simulation':
"Traceback (most recent call last):
  File "OpenDECT_v1.py", line 1073, in Simulate
    RunEclipse("temp/CORE_TEST-0.DATA")
  File "/OpenDect/Tools/CoreSimulation.py", line 227, in RunEclipse
    subprocess.call(args, stdout=FNULL)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory"
Any suggestion ?
Thanks

**Comment by mtembel** [comment]
also:
$ flow CORE_TEST-0.DATA 
**********************************************************************
*                                                                    *
*              This is flow_ebos (version 2017.10-pre)               *
*            (eWoms version: 2017.10-pre ("Buddy Holly"))            *
*                                                                    *
* Flow is a simulator for fully implicit three-phase black-oil flow, *
*            and is part of OPM. For more information see:           *
*                       http://opm-project.org                       *
*                                                                    *
**********************************************************************

Reading the deck file 'CORE_TEST-0.DATA'
Program threw an exception: PARSE_UNKNOWN_KEYWORD: Keyword LAB not recognized.

**Comment by Thif** [comment]
Yeah that s a bit tricky ...
The intention was to use OPM flow to run the simulation, but I ended up calling schlumberger eclipse via the "subprocess" command in Linux.
Eclipse runs that way on my Linux machine but of course this is not scalable :(

**Comment by alfbr** [comment]
It seems you are using an Eclipse keyword not yet supported by flow. Please consult the manual here:
https://opm-project.org/?page_id=955
to see what is supported, and edit your DATA file to make it run.

**Comment by mtembel** [comment]
Thanks for your prompt reply, actually the DATA file is the one generated by OpenDec (which includes some eclipse keyword not supported by flow), I will edit the file accordingly...
Thanks
